"""empty message

Revision ID: 44f1d313fc2a
Revises: 2a5c354951c6
Create Date: 2025-12-27 19:08:28.095923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44f1d313fc2a'
down_revision = '2a5c354951c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('diajukan', 'diproses', 'selesai', collation='utf8mb4_general_ci'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('diajukan', 'diproses', 'selesai', collation='utf8mb4_general_ci'),
               nullable=True)

    # ### end Alembic commands ###
