"""add keterangan dan tanggal status laporan

Revision ID: 58aa26ecb267
Revises: 44f1d313fc2a
Create Date: 2026-01-08 22:07:40.734199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aa26ecb267'
down_revision = '44f1d313fc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ringkasan_hasil', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('alasan_ditolak', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tgl_diproses', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tgl_selesai', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tgl_ditolak', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_column('tgl_ditolak')
        batch_op.drop_column('tgl_selesai')
        batch_op.drop_column('tgl_diproses')
        batch_op.drop_column('alasan_ditolak')
        batch_op.drop_column('ringkasan_hasil')

    # ### end Alembic commands ###
