"""add foto_admin

Revision ID: abfcc27cb519
Revises: 58aa26ecb267
Create Date: 2026-01-15 15:42:10.444827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfcc27cb519'
down_revision = '58aa26ecb267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_admin', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_column('foto_admin')

    # ### end Alembic commands ###
